#!/bin/sh

set -e

#DEBHELPER#

pycentral pkginstall python-carbon

for i in `find /var/lib/graphite` ; do
    # only do something when no setting exists
    if ! dpkg-statoverride --list $i >/dev/null 2>&1; then
        dpkg-statoverride --update --add www-data www-data 4755 $i
    fi

    if ! dpkg-statoverrid --list /var/log/graphite >/dev/null 2>&1; then
	dpkg-statoverride --update --add www-data www-data 4750 /var/log/graphite
    fi
done

exit 0
