#!/bin/sh

set -e

#DEBHELPER#

#update-python-modules --post-install

for i in `find /var/lib/graphite` ; do
    # only do something when no setting exists
    if ! dpkg-statoverride --list $i >/dev/null 2>&1; then
        dpkg-statoverride --update --add www-data www-data 4755 $i
    fi
done

exit 0
